begin;

create table if not exists public.generation_usage (
  id bigint generated by default as identity primary key,
  ip_address inet not null,
  quota_date date not null,
  created_at timestamptz not null default now()
);

comment on table public.generation_usage is
  'Tracks successful quota reservations for recipe generation.';

create index if not exists generation_usage_quota_date_idx
  on public.generation_usage (quota_date);

create index if not exists generation_usage_ip_quota_date_idx
  on public.generation_usage (ip_address, quota_date);

alter table public.generation_usage enable row level security;

revoke all on table public.generation_usage from anon, authenticated;
grant select, insert, delete on table public.generation_usage to service_role;

create or replace function public.consume_generation_quota(p_ip_address text)
returns table (
  allowed boolean,
  rejection_code text,
  remaining_for_ip integer,
  remaining_system_wide integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  parsed_ip_address inet;
  current_quota_date date := timezone('Europe/Berlin', now())::date;
  current_ip_count integer;
  current_system_count integer;
begin
  if p_ip_address is null or btrim(p_ip_address) = '' then
    return query
      select false, 'INVALID_IP_ADDRESS'::text, 0, 0;
    return;
  end if;

  begin
    parsed_ip_address := btrim(p_ip_address)::inet;
  exception
    when invalid_text_representation then
      return query
        select false, 'INVALID_IP_ADDRESS'::text, 0, 0;
      return;
  end;

  perform pg_advisory_xact_lock(
    hashtext('recipe-generation-quota-' || current_quota_date::text)
  );

  delete from public.generation_usage
  where quota_date < current_quota_date - 7;

  select count(*)::integer
  into current_ip_count
  from public.generation_usage
  where ip_address = parsed_ip_address
    and quota_date = current_quota_date;

  select count(*)::integer
  into current_system_count
  from public.generation_usage
  where quota_date = current_quota_date;

  if current_ip_count >= 3 then
    return query
      select
        false,
        'IP_DAILY_LIMIT_REACHED'::text,
        0,
        greatest(0, 12 - current_system_count);
    return;
  end if;

  if current_system_count >= 12 then
    return query
      select
        false,
        'SYSTEM_DAILY_LIMIT_REACHED'::text,
        greatest(0, 3 - current_ip_count),
        0;
    return;
  end if;

  insert into public.generation_usage (ip_address, quota_date)
  values (parsed_ip_address, current_quota_date);

  return query
    select
      true,
      null::text,
      greatest(0, 3 - current_ip_count - 1),
      greatest(0, 12 - current_system_count - 1);
end;
$$;

comment on function public.consume_generation_quota(text) is
  'Atomically reserves one of three daily IP slots and one of twelve system-wide slots.';

revoke all on function public.consume_generation_quota(text)
  from public, anon, authenticated;

grant execute on function public.consume_generation_quota(text)
  to service_role;

create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  generation_id text not null,
  created_at timestamptz not null default now(),

  title text not null
    check (char_length(trim(title)) between 1 and 160),

  summary text not null
    check (char_length(trim(summary)) between 1 and 600),

  cuisine_style text not null
    check (
      cuisine_style in (
        'german',
        'italian',
        'indian',
        'japanese',
        'gourmet',
        'fusion'
      )
    ),

  diet_preference text not null
    check (
      diet_preference in (
        'vegetarian',
        'vegan',
        'keto',
        'unrestricted'
      )
    ),

  cooking_time_category text not null
    check (
      cooking_time_category in (
        'quick',
        'medium',
        'complex'
      )
    ),

  cooking_time_minutes integer not null
    check (cooking_time_minutes between 1 and 240),

  portion_count integer not null
    check (portion_count between 1 and 12),

  cooking_people_count integer not null
    check (cooking_people_count between 1 and 3),

  used_ingredient_percentage integer not null
    check (used_ingredient_percentage between 0 and 100),

  available_ingredients jsonb not null
    check (jsonb_typeof(available_ingredients) = 'array'),

  additional_ingredients jsonb not null
    check (
      jsonb_typeof(additional_ingredients) = 'array'
      and jsonb_array_length(additional_ingredients) <= 3
    ),

  nutrition_per_portion jsonb not null
    check (jsonb_typeof(nutrition_per_portion) = 'object'),

  nutrition_total jsonb not null
    check (jsonb_typeof(nutrition_total) = 'object'),

  steps jsonb not null
    check (
      jsonb_typeof(steps) = 'array'
      and jsonb_array_length(steps) between 2 and 12
    ),

  image_url text,

  likes_count integer not null default 0
    check (likes_count >= 0),

  is_public boolean not null default true
);

comment on table public.recipes is
  'Stores validated AI-generated recipes for results and the public cookbook.';

create index if not exists recipes_generation_id_idx
  on public.recipes (generation_id);

create index if not exists recipes_public_cuisine_created_at_idx
  on public.recipes (cuisine_style, created_at desc)
  where is_public = true;

create index if not exists recipes_public_likes_idx
  on public.recipes (likes_count desc, created_at desc)
  where is_public = true;

alter table public.recipes enable row level security;

revoke all on table public.recipes from anon, authenticated;

grant select on table public.recipes to anon, authenticated;
grant select, insert, update, delete on table public.recipes to service_role;

drop policy if exists "Public recipes are readable"
  on public.recipes;

create policy "Public recipes are readable"
  on public.recipes
  for select
  to anon, authenticated
  using (is_public = true);

commit;

